//go:binary-only-package
package swarm

import (
	_ "bytes"
	_ "context"
	_ "crypto/ecdsa"
	_ "fmt"
	_ "io"
	_ "math/big"
	_ "net"
	_ "path/filepath"
	_ "strings"
	_ "time"
	_ "unicode"

	_ "github.com/ethereum/go-ethereum/accounts/abi/bind"
	_ "github.com/ethereum/go-ethereum/common"
	_ "github.com/ethereum/go-ethereum/contracts/chequebook"
	_ "github.com/ethereum/go-ethereum/contracts/ens"
	_ "github.com/ethereum/go-ethereum/ethclient"
	_ "github.com/ethereum/go-ethereum/metrics"
	_ "github.com/ethereum/go-ethereum/p2p"
	_ "github.com/ethereum/go-ethereum/p2p/discover"
	_ "github.com/ethereum/go-ethereum/p2p/protocols"
	_ "github.com/ethereum/go-ethereum/params"
	_ "github.com/ethereum/go-ethereum/rpc"
	_ "github.com/ethereum/go-ethereum/swarm/api"
	_ "github.com/ethereum/go-ethereum/swarm/api/http"
	_ "github.com/ethereum/go-ethereum/swarm/fuse"
	_ "github.com/ethereum/go-ethereum/swarm/log"
	_ "github.com/ethereum/go-ethereum/swarm/network"
	_ "github.com/ethereum/go-ethereum/swarm/network/stream"
	_ "github.com/ethereum/go-ethereum/swarm/pss"
	_ "github.com/ethereum/go-ethereum/swarm/state"
	_ "github.com/ethereum/go-ethereum/swarm/storage"
	_ "github.com/ethereum/go-ethereum/swarm/storage/mock"
	_ "github.com/ethereum/go-ethereum/swarm/storage/mru"
	_ "github.com/ethereum/go-ethereum/swarm/tracing"
)
