//go:binary-only-package
package core

import (
	_ "bytes"
	_ "container/heap"
	_ "context"
	_ "crypto/rand"
	_ "encoding/binary"
	_ "encoding/hex"
	_ "encoding/json"
	_ "errors"
	_ "fmt"
	_ "io"
	_ "math"
	_ "math/big"
	_ "math/rand"
	_ "os"
	_ "runtime"
	_ "sort"
	_ "strconv"
	_ "strings"
	_ "sync"
	_ "sync/atomic"
	_ "time"

	_ "github.com/hashicorp/golang-lru"

	_ "github.com/ethereum/go-ethereum/common"
	_ "github.com/ethereum/go-ethereum/common/hexutil"
	_ "github.com/ethereum/go-ethereum/common/math"
	_ "github.com/ethereum/go-ethereum/common/mclock"
	_ "github.com/ethereum/go-ethereum/common/prque"
	_ "github.com/ethereum/go-ethereum/consensus"
	_ "github.com/ethereum/go-ethereum/consensus/misc"
	_ "github.com/ethereum/go-ethereum/core/rawdb"
	_ "github.com/ethereum/go-ethereum/core/state"
	_ "github.com/ethereum/go-ethereum/core/types"
	_ "github.com/ethereum/go-ethereum/core/vm"
	_ "github.com/ethereum/go-ethereum/crypto"
	_ "github.com/ethereum/go-ethereum/ethdb"
	_ "github.com/ethereum/go-ethereum/event"
	_ "github.com/ethereum/go-ethereum/log"
	_ "github.com/ethereum/go-ethereum/metrics"
	_ "github.com/ethereum/go-ethereum/params"
	_ "github.com/ethereum/go-ethereum/rlp"
	_ "github.com/ethereum/go-ethereum/trie"
)

