//go:binary-only-package
package api

import (
	_ "archive/tar"
	_ "bufio"
	_ "bytes"
	_ "context"
	_ "crypto/ecdsa"
	_ "crypto/rand"
	_ "encoding/binary"
	_ "encoding/hex"
	_ "encoding/json"
	_ "errors"
	_ "fmt"
	_ "io"
	_ "math/big"
	_ "mime"
	_ "net/http"
	_ "os"
	_ "path"
	_ "path/filepath"
	_ "regexp"
	_ "strings"
	_ "sync"
	_ "time"

	_ "github.com/opentracing/opentracing-go"
	_ "golang.org/x/crypto/scrypt"
	_ "gopkg.in/urfave/cli.v1"

	_ "github.com/ethereum/go-ethereum/common"
	_ "github.com/ethereum/go-ethereum/contracts/ens"
	_ "github.com/ethereum/go-ethereum/core/types"
	_ "github.com/ethereum/go-ethereum/crypto"
	_ "github.com/ethereum/go-ethereum/crypto/ecies"
	_ "github.com/ethereum/go-ethereum/crypto/sha3"
	_ "github.com/ethereum/go-ethereum/metrics"
	_ "github.com/ethereum/go-ethereum/node"
	_ "github.com/ethereum/go-ethereum/p2p/discover"
	_ "github.com/ethereum/go-ethereum/swarm/log"
	_ "github.com/ethereum/go-ethereum/swarm/multihash"
	_ "github.com/ethereum/go-ethereum/swarm/network"
	_ "github.com/ethereum/go-ethereum/swarm/pss"
	_ "github.com/ethereum/go-ethereum/swarm/sctx"
	_ "github.com/ethereum/go-ethereum/swarm/services/swap"
	_ "github.com/ethereum/go-ethereum/swarm/spancontext"
	_ "github.com/ethereum/go-ethereum/swarm/storage"
	_ "github.com/ethereum/go-ethereum/swarm/storage/encryption"
	_ "github.com/ethereum/go-ethereum/swarm/storage/mru"
)
