//go:binary-only-package
package discv5

import (
	_ "bytes"
	_ "container/heap"
	_ "crypto/ecdsa"
	_ "crypto/elliptic"
	_ "crypto/rand"
	_ "encoding/binary"
	_ "encoding/hex"
	_ "errors"
	_ "fmt"
	_ "math"
	_ "math/big"
	_ "math/rand"
	_ "net"
	_ "net/url"
	_ "os"
	_ "regexp"
	_ "sort"
	_ "strconv"
	_ "strings"
	_ "sync"
	_ "time"

	_ "github.com/syndtr/goleveldb/leveldb"
	_ "github.com/syndtr/goleveldb/leveldb/errors"
	_ "github.com/syndtr/goleveldb/leveldb/iterator"
	_ "github.com/syndtr/goleveldb/leveldb/opt"
	_ "github.com/syndtr/goleveldb/leveldb/storage"
	_ "github.com/syndtr/goleveldb/leveldb/util"

	_ "github.com/ethereum/go-ethereum/common"
	_ "github.com/ethereum/go-ethereum/common/mclock"
	_ "github.com/ethereum/go-ethereum/crypto"
	_ "github.com/ethereum/go-ethereum/crypto/sha3"
	_ "github.com/ethereum/go-ethereum/log"
	_ "github.com/ethereum/go-ethereum/metrics"
	_ "github.com/ethereum/go-ethereum/p2p/nat"
	_ "github.com/ethereum/go-ethereum/p2p/netutil"
	_ "github.com/ethereum/go-ethereum/rlp"
)
